### ISSUE TITLE
2-master won't start (2.4.3)

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-user-env#116]
trying to start 2-master (2.4.3) started to produce this error
```
/trezor-user-env/src/binaries/firmware/bin/trezor-emu-core-v2-master: /nix/store/sbbifs2ykc05inws26203h0xwcadnf0l-glibc-2.32-46/lib/libc.so.6: version `GLIBC_2.33' not found (required by 
```

cc @tsusanka

**Comment by tsusanka** [comment]
@mmilata this is how we currently patch all firmware binaries:

https://github.com/trezor/trezor-user-env/blob/d45d9940d7f657d3117de229fe7e7d133e9ef02c/src/binaries/firmware/bin/download.sh#L43

Should we add something new?

**Comment by vdovhanych** [comment]
I'm starting to think that this issue is with updating glib in `trezor-firmware`. The one from unstable is used to build it, and we're using the stable release channel for our docker image. That's what nixos provides.  The version of `ldd` in 21.05 (stable) is `2.32`, and the one it's asking for is `2.33`, which is in unstable, and it can't launch as that version is not present there.

**Comment by vdovhanych** [comment]
Yep, I just confirmed it on my end. The emulator works after you patch it with `glib 2.33`. We need to add that version somehow to the base docker image in which the trezor-user-env is built. I will try to do it tomorrow morning, calling it a quits for today.
![Screenshot-20211123214207-1363x991](https://user-images.githubusercontent.com/45185420/143108219-fe37cb0a-7e51-4b5e-9050-7bb3cd3bcd64.png)

**Comment by tsusanka** [comment]
Btw @mroz22 has our Connect / Suite tests failed? They should have, right?

**Comment by mroz22** [comment]
> Btw @mroz22 has our Connect / Suite tests failed? They should have, right?

yes.

**Comment by tsusanka** [comment]
I want to have a look at this again due to https://github.com/trezor/trezor-user-env/pull/117#issuecomment-977669925.
