### ISSUE TITLE
proxy.py does not mimic failed cases bahaviour correctly

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-user-env#43]
I don't speak snake tongue very well but I bumped into few problems when I switched to using proxy in trezor-suite. 

Let's say you want to test an edge case when user stops bridge or basically any non 200 response. I suspect that you fall into this catch block 
https://github.com/trezor/trezor-user-env/blob/b64cd7c63c84d89c135987d963b314c292189539/controller/proxy.py#L64-L67
but response generated by this proxy server is not the same as you would have received if proxy was not there.

**Comment by tsusanka** [comment]
Correct, catching general Exception is a bad idea in general. It should send the same error response as the origin. I'll have a look

**Comment by tsusanka** [comment]
We have agreed we will turn off the Bridge proxy every time Bridge is being turned off. Needs #45 before.

Drafted in https://github.com/trezor/trezor-user-env/tree/tsusanka/servers. To be reviewed and checked against suite.

**Comment by grdddj** [comment]
Hello, I tried to play with this a little bit (using the _/status/_ GET endpoint ) and here are my observations:
- in cases when the "normal" bridge on 0.0.0.0:21325 is online, **it is correctly relaying even non-200 responses** - as this is NOT being handled in the _except_ case (it does not throw any python Exception - non-200 response does not raise it by default)
- when the bridge is unreachable at that port (I simulated it below by changing the port to 21327), it send that 404 message and specifies the error
  - **how would we like to handle it?**
  - if it should really mimic the bridge, we can theoretically **get rid of the Exception handling** (or just log the exception and raise), so that any possible thrown exception in the bridge will cause the same exception in the proxy (this way it would really mimic the bridge itself as closely as possible)

![image](https://user-images.githubusercontent.com/42543243/125162810-36705500-e18a-11eb-9232-c6e06b0d7683.png)

**Comment by tsusanka** [comment]
I think this is solved by #58 in the `incoming` branch (will be merged to `master` after stabilized)? Because there we have separated the dashboard and the bridge proxy so the bridge proxy is not running when bridge is not started. Which seems to me what was @mroz22's problem.. :thinking:
