### ISSUE TITLE
Rewrite websockets to use a library

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#47]
Drafted in https://github.com/trezor/trezor-user-env/tree/tsusanka/servers. To be reviewed and checked against suite.

**Comment by szymonlesisz** [comment]
make sure that health-check is working with new websocket server:
https://github.com/trezor/trezor-user-env/commit/619b5a10f72512f2cb65c34d36ca11352367e66d

**Comment by tsusanka** [comment]
@grdddj could you please verify what @szymonlesisz was commeting?

**Comment by grdddj** [comment]
> @grdddj could you please verify what @szymonlesisz was commeting? Because other than that I think this is done.

Seems that we want some simple HTTP health-check, so that we do not need to connect properly to the websocket to find out it is running.

Turns out we can incorporate extra HTTP endpoint in the websocket server, like [this](https://websockets.readthedocs.io/en/stable/deployment.html#port-sharing).

@szymonlesisz Is it OK for you to receive OK on `localhost:9001/health/`? I already included this in PR #73 

![image](https://user-images.githubusercontent.com/42543243/125189313-bacce180-e237-11eb-8438-1877ade2b137.png)

**Comment by szymonlesisz** [comment]
sorry somehow i missed this thread.
i already did some curl check on the connect side:
https://github.com/trezor/connect/blob/develop/tests/run.sh#L47-L65

basically if websocket server is running it will return an error with `Upgrade: websocket` header.
connect is sending regular http request via `curl` and fails since user-env websocket server is expecting different headers (websocket handshake)

so the answer is - either we use this piece of code from connect in user-env to determine if websocket is running or we leave it as it is now

**Comment by grdddj** [comment]
If the `connect` side is alright with the current status, we can leave it, not to introduce unnecessary code. That would mean closing this issue and cancelling the PR #73

**Comment by tsusanka** [comment]
I agree with @grdddj, let's keep it as is.
