### ISSUE TITLE
Use Python logging module instead of dyi log function

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#70]
In https://github.com/trezor/trezor-user-env/pull/58 (https://github.com/trezor/trezor-user-env/commit/ff58cb715dd1ff82beba60689d0b556e78fe5ca6 in particular) we have introduced a new function `log`. Shouldn't we replace with Python's [logging module](https://docs.python.org/3/library/logging.html)?

**Comment by grdddj** [comment]
I was thinking about this a little bit, as I saw the TODO we had above the previous log() function in controller, but then I deleted the TODO for some reasons:
- we are only using the print() one time in the helper module, all others are importing it from there (the exception is `binaries.py` - [here](https://github.com/trezor/trezor-user-env/pull/58/files#diff-162dc995d912e7aee13343319d2ffc8c8663f66bdf317ef46c7b57411eab0992R42) because there we want to color just part of the output, not the whole string, and also combine multiple colors in one line)
- even though the logging can be configured to print into stdout, I am not sure it could handle the coloring
- we are currently not saving the logs into a file

I would say the logging module has big benefits in bigger projects, where we want to keeps log persistently in a debugging file (which we can theoretically do even here, if the users will find benefits in that). Also, the possibility of using severity levels is quite nice, that could be a reason to implement it here - split logs into DEBUG, INFO, CRITICAL etc. (which would be visible even in terminal and add quick info for user)

**Comment by grdddj** [comment]
Some research for including colors while using logging module:
- nice [SO thread](https://stackoverflow.com/questions/384076/how-can-i-color-python-logging-output) about it
  - mainly [this answer](https://stackoverflow.com/questions/384076/how-can-i-color-python-logging-output/56944256#56944256)
- however, none of those seem to to have the same problem as we do - they are trying to map colors to individual logging levels (INFO is grey, WARNING is yellow, CRITICAL is red, etc.) - but we want to separate colors mostly based on modules the messages come from, not on logging severity (partly that as well, as we are using red color for error messages coming from whatever module)

My conclusion so far is that *currently* there is no need to switch into logging, but it may very well change in the future, when (if) we get more precise specification from our users

**Comment by tsusanka** [comment]
Ok sounds good. Although I am wondering if this will change with https://github.com/satoshilabs/devops/issues/37. Again please discuss with @vdovhanych if needed :).

**Comment by tsusanka** [comment]
@grdddj I think we can close this one as well, right?

**Comment by grdddj** [comment]
> @grdddj I think we can close this one as well, right?

I would say so, the logging is already implemented and it server a good purpose.
