### ISSUE TITLE
Receive and log test scenario name/description from Suite e2e tests

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#82]
It would be helpful for debugging purposes to send the test scenario name or small description from Suite tests to the websocket. Websocket would log this unique test identifier, so we would quickly know where to look in our logs.

Steps:
- create method in controller with a command like "log_test_details", receiving a string and logging it
- create Cypress task in Suite calling this websocket "endpoint"
- at the start of each Suite test, call this function to send unique test name/description (could also act as a nice extra documentation for that testing scenario)

**Comment by tsusanka** [comment]
I am thinking we could even somehow enforce it. For example the client would have to send "hello" with these details and we would respond with [welcome](https://github.com/trezor/trezor-user-env/blob/f67ba1ca434dbcfaad95c0a4b1ba070a9dbb7e49/src/controller.py#L183). All other commands would raise an error until this is sent, what do you think? It seems better to enforce it otherwise it can get messy when debugging where one test sends it and the other does not and you do not know such feature in trezor-user-env.

**Comment by grdddj** [comment]
If it could be enforced, even better. However, then the websocket would lose its stateless status, as it would need to remember which clients already sent this `hello` and which not.

Certainly something for discussion.
