### ISSUE TITLE
More start notes 

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#95]
Some users were confused by "Starting trezor-user-env server" as they were waiting and waiting. Maybe we could keep that but also add:
- "Controller started at.."

and

- "Dashboard started at .."
?

**Comment by grdddj** [comment]
We already have both (the `Controller starting` and `Dashboard starting`) in their separate python files in `start()` functions.

I guess the problem is that these logs **are not being printed into the console** when running `docker compose up` (it really ends with `Starting trezor-user-env server`)

What we can do:
- change the print for example to `Trezor-user-env server started`
https://github.com/trezor/trezor-user-env/blob/8ff3d21f7d39e48fea7de58e406457e155147261/run.sh#L19
- somehow make sure the logs from python scripts are properly visible in `docker compose` output

**Comment by tsusanka** [comment]
> I guess the problem is that these logs are not being printed into the console when running docker compose up (it really ends with Starting trezor-user-env server)

Btw do we know why these get printed and the following not? :thinking:

**Comment by grdddj** [comment]
> Btw do we know why these get printed and the following not? thinking

I do not, but it seems the difference is in origin of these logs -  the visible ones are from `run.sh`, and the "invisible" ones come from all the python files.

As if the docker-compose was ignoring the python logs - there are a lot of possible reasons (can be caused by the coloring for example). We would need to investigate this (so this would be the core of this issue).
